#!/usr/bin/env bash
cp -n $PWD/files/gitconfig ~/.gitconfig
ln -f -s $PWD/files/gitconfig_generic ~/.gitconfig_generic
ln -f -s $PWD/files/gitconfig.for_$(uname) ~/.gitconfig_platform_specific
cp -n $PWD/files/gitconfig_credentials ~/.gitconfig_credentials

ln -f -s $PWD/files/gitignore_global ~/.gitignore_global
ln -f -s $PWD/files/git_commit_template.txt ~/.git_commit_template.txt
curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -o ~/.git-completion.bash
