#!/usr/bin/env bash

if [[ -r ~/.vimrc ]]; then
    mv ~/.vimrc ~/.vimrc.$(date +%Y-%m-%d.%H-%M)
fi
ln -sf $PWD/vimrc ~/.vimrc
cp $PWD/vim_colorscheme.example ~/.vim_colorscheme

rm -rf ~/.vim
mkdir ~/.vim
