#!/usr/bin/env bash
# ------------------------------------------------------------------------------
# Configure and install basic softwares in macOS through command line.
# ------------------------------------------------------------------------------

PYTHON_VERSION=3.8


# =====================
# Basic stuff
# =====================

# Make bash the default shell
chsh -s /bin/bash


# Xcode
# -----

if ! xcode-select -p >/dev/null 2>&1; then
    echo "You must install Xcode first"
    exit 1;
fi

sudo xcodebuild -license accept


# Homebrew
# --------

# Install homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew doctor


# ===========================
# Python
# ===========================


# Pyenv
# -----

brew install openssl readline sqlite3 xz zlib
brew install pyenv
eval "$(pyenv init --path)"
hash -r

git clone https://github.com/momo-lab/xxenv-latest.git "$(pyenv root)"/plugins/xxenv-latest
pyenv latest install ${PYTHON_VERSION}
pyenv latest global

git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv


# pipx
# ----

brew install pipx
pipx ensurepath

# Other Python related
# --------------------

pipx install black
pipx install isort
pipx install docformatter


# =================
# Other tools
# =================

brew install wget tree git
brew install ag ack
brew install difftastic
brew install tmux
brew install macvim
brew install ctags
brew install bash-completion

brew install --cask iterm2
brew install --cask firefox
brew install --cask google-chrome
brew install --cask dbeaver-community
brew install --cask telegram
brew install --cask the-unarchiver
brew install youtube-dl
brew install ffmpeg

brew install --cask docker
brew install --cask virtualbox
brew install --cask vagrant

brew tap homebrew/cask-fonts
brew install svn font-ibm-plex-mono

