__avoid_path_pile_up () {
    # Path pile ups when a login shell is invoked from an active shell.
    # Example: when you call tmux from the command line.
    #
    # So, what exactly is a "path pile up"? 
    # It is what happens when you already have PATH set and scripts responsible
    # to set the PATH are called again. They are usually .bash_profile 
    # or .profile 
    if [[ -z "$ORIGINAL_PATH" ]]; then
        export ORIGINAL_PATH="$PATH"
    fi
    PATH="$ORIGINAL_PATH"
}

__avoid_path_pile_up

eval "$(/opt/homebrew/bin/brew shellenv)"
. /opt/homebrew/opt/asdf/libexec/asdf.sh

# Created by `pipx` on 2023-04-13 22:48:39
#export PATH="$PATH:/Users/viniciusban/.local/bin"
export PATH="/Users/viniciusban/.local/bin:$PATH"

. ~/.bashrc
