#!/usr/bin/env bash

if [[ "$(uname)" = "Darwin" ]]; then
    filename=~/.bashrc
else
    filename=~/.bash_aliases
fi

if [ ! -L ${filename} -a -f ${filename} ]; then
    mv ${filename} ${filename}.$(date +%Y-%m-%d.%H-%M)
fi

ln -sf ${PWD}/bashrc ${filename}

cp -n ${PWD}/ps1_customizations.example ~/.ps1_customizations
cp -n ${PWD}/pyenv_global_command.example ~/.pyenv_global_command
